// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: proto/hass.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Home Assistant Events
type EventSubscriberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *EventSubscriberRequest) Reset() {
	*x = EventSubscriberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hass_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventSubscriberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSubscriberRequest) ProtoMessage() {}

func (x *EventSubscriberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hass_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSubscriberRequest.ProtoReflect.Descriptor instead.
func (*EventSubscriberRequest) Descriptor() ([]byte, []int) {
	return file_proto_hass_proto_rawDescGZIP(), []int{0}
}

func (x *EventSubscriberRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string     `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data *anypb.Any `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hass_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hass_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_hass_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetData() *anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

// Home Assistant Services
type ServiceCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain  string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Service string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	// Types that are assignable to Target:
	//
	//	*ServiceCall_AreaId
	//	*ServiceCall_DeviceId
	//	*ServiceCall_EntityId
	//	*ServiceCall_LabelId
	Target   isServiceCall_Target `protobuf_oneof:"target"`
	JsonData string               `protobuf:"bytes,7,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"`
	Returns  bool                 `protobuf:"varint,8,opt,name=returns,proto3" json:"returns,omitempty"`
}

func (x *ServiceCall) Reset() {
	*x = ServiceCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hass_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCall) ProtoMessage() {}

func (x *ServiceCall) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hass_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCall.ProtoReflect.Descriptor instead.
func (*ServiceCall) Descriptor() ([]byte, []int) {
	return file_proto_hass_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceCall) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ServiceCall) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (m *ServiceCall) GetTarget() isServiceCall_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (x *ServiceCall) GetAreaId() string {
	if x, ok := x.GetTarget().(*ServiceCall_AreaId); ok {
		return x.AreaId
	}
	return ""
}

func (x *ServiceCall) GetDeviceId() string {
	if x, ok := x.GetTarget().(*ServiceCall_DeviceId); ok {
		return x.DeviceId
	}
	return ""
}

func (x *ServiceCall) GetEntityId() string {
	if x, ok := x.GetTarget().(*ServiceCall_EntityId); ok {
		return x.EntityId
	}
	return ""
}

func (x *ServiceCall) GetLabelId() string {
	if x, ok := x.GetTarget().(*ServiceCall_LabelId); ok {
		return x.LabelId
	}
	return ""
}

func (x *ServiceCall) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

func (x *ServiceCall) GetReturns() bool {
	if x != nil {
		return x.Returns
	}
	return false
}

type isServiceCall_Target interface {
	isServiceCall_Target()
}

type ServiceCall_AreaId struct {
	AreaId string `protobuf:"bytes,3,opt,name=area_id,json=areaId,proto3,oneof"`
}

type ServiceCall_DeviceId struct {
	DeviceId string `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3,oneof"`
}

type ServiceCall_EntityId struct {
	EntityId string `protobuf:"bytes,5,opt,name=entity_id,json=entityId,proto3,oneof"`
}

type ServiceCall_LabelId struct {
	LabelId string `protobuf:"bytes,6,opt,name=label_id,json=labelId,proto3,oneof"`
}

func (*ServiceCall_AreaId) isServiceCall_Target() {}

func (*ServiceCall_DeviceId) isServiceCall_Target() {}

func (*ServiceCall_EntityId) isServiceCall_Target() {}

func (*ServiceCall_LabelId) isServiceCall_Target() {}

type ServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JsonData string `protobuf:"bytes,1,opt,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"`
}

func (x *ServiceResponse) Reset() {
	*x = ServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hass_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse) ProtoMessage() {}

func (x *ServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hass_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_hass_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceResponse) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

var File_proto_hass_proto protoreflect.FileDescriptor

var file_proto_hass_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x61, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x68, 0x61, 0x73, 0x73, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x16, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x45, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x28,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41,
	0x6e, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xf6, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x61, 0x72,
	0x65, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x61,
	0x72, 0x65, 0x61, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x09, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x08, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x73, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x22, 0x2e, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6a, 0x73, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6a, 0x73, 0x6f, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x32, 0x42, 0x0a, 0x06, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x1c, 0x2e, 0x68, 0x61, 0x73, 0x73, 0x2e,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e, 0x68, 0x61, 0x73, 0x73, 0x2e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x30, 0x01, 0x32, 0x43, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x12, 0x37, 0x0a, 0x0b, 0x43, 0x61, 0x6c, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x11, 0x2e, 0x68, 0x61, 0x73, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43,
	0x61, 0x6c, 0x6c, 0x1a, 0x15, 0x2e, 0x68, 0x61, 0x73, 0x73, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_hass_proto_rawDescOnce sync.Once
	file_proto_hass_proto_rawDescData = file_proto_hass_proto_rawDesc
)

func file_proto_hass_proto_rawDescGZIP() []byte {
	file_proto_hass_proto_rawDescOnce.Do(func() {
		file_proto_hass_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_hass_proto_rawDescData)
	})
	return file_proto_hass_proto_rawDescData
}

var file_proto_hass_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_hass_proto_goTypes = []interface{}{
	(*EventSubscriberRequest)(nil), // 0: hass.EventSubscriberRequest
	(*Event)(nil),                  // 1: hass.Event
	(*ServiceCall)(nil),            // 2: hass.ServiceCall
	(*ServiceResponse)(nil),        // 3: hass.ServiceResponse
	(*anypb.Any)(nil),              // 4: google.protobuf.Any
}
var file_proto_hass_proto_depIdxs = []int32{
	4, // 0: hass.Event.data:type_name -> google.protobuf.Any
	0, // 1: hass.Events.Subscribe:input_type -> hass.EventSubscriberRequest
	2, // 2: hass.Services.CallService:input_type -> hass.ServiceCall
	1, // 3: hass.Events.Subscribe:output_type -> hass.Event
	3, // 4: hass.Services.CallService:output_type -> hass.ServiceResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_hass_proto_init() }
func file_proto_hass_proto_init() {
	if File_proto_hass_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_hass_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventSubscriberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hass_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hass_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hass_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_hass_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ServiceCall_AreaId)(nil),
		(*ServiceCall_DeviceId)(nil),
		(*ServiceCall_EntityId)(nil),
		(*ServiceCall_LabelId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_hass_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_hass_proto_goTypes,
		DependencyIndexes: file_proto_hass_proto_depIdxs,
		MessageInfos:      file_proto_hass_proto_msgTypes,
	}.Build()
	File_proto_hass_proto = out.File
	file_proto_hass_proto_rawDesc = nil
	file_proto_hass_proto_goTypes = nil
	file_proto_hass_proto_depIdxs = nil
}
