---
build_from:
  aarch64: ghcr.io/hassio-addons/ubuntu-base:10.0.1
  amd64: ghcr.io/hassio-addons/ubuntu-base:10.0.1
  armv7: ghcr.io/hassio-addons/ubuntu-base:10.0.1
codenotary:
  base_image: rick@moonen.network
  signer: rick@moonen.network