---
name: "gRPC Bridge"
# yamllint disable-line rule:line-length
description: "Service that acts as a bridge between Home Assistant and other services. Translating gRPC calls into WebSocket commands."
version: dev
slug: "grpc_bridge"
init: false
arch:
  - aarch64
  - amd64
  - armv7
homeassistant_api: true
ports:
  9091/tcp: 9091
ports_description:
  9091/tcp: gRPC
