---
name: "gRPC Bridge"
# yamllint disable-line rule:line-length
description: "Use gRPC calls to control and react to Home Assistant events, entities and more"
version: dev
url: https://github.com/moonen-home-automation/grpc-bridge
slug: "grpc-bridge"
init: false
arch:
  - aarch64
  - amd64
  - armv7
homeassistant_api: true
ports:
  9091/tcp: 9091
ports_description:
  9091/tcp: gRPC
